### ISSUE TITLE
Selection applied to all of the networks with same name

### ISSUE THREAD

**Issue by keiono** [cyComponent/NDExValet#2]
![2016-06-14 12 53 36](https://cloud.githubusercontent.com/assets/73890/16057456/0efd10d6-322f-11e6-9c00-06b9619e8a4d.png)

The screenshot above is the table after the first selection (clicked __BARD1 Signalling Events__).  It selects all networks with same title, which is confusing for users.  Selection should be applied to (internal) unique IDs.

**Comment by ericsage** [comment]
I've fixed this in the latest commit by using externalId instead of the network name
