### ISSUE TITLE
Select all check box does not update cart

### ISSUE THREAD

**Issue by keiono** [cyComponent/NDExValet#7]
![2016-06-22 18 51 14](https://cloud.githubusercontent.com/assets/73890/16289480/557d4716-38aa-11e6-90e2-d85f6eb56585.png)

Even if I click the _select all_ checkbox, it does not update cart (remains 0).

**Comment by ericsage** [comment]
I removed the select all checkbox on the table. I don't think this will be a needed feature. If at some point someone requests it, we can add it back in and implement the logic.
